[env:nodemcuv2]
platform     = espressif8266
board        = nodemcuv2
framework    = arduino

monitor_speed = 115200
upload_speed  = 115200

lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.10
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.5
