[env:nodemcuv2]
platform     = espressif8266
board        = nodemcuv2
framework    = arduino

monitor_speed = 115200
upload_speed  = 115200

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.5
